# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [bic, usaa]
patreon: # Replace with a single Patreon username mouse3687
open_collective: # Replace with a single Open Collective username vodoo.io
ko_fi: # Replace with a single Ko-fi username ISO
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel -runtime
community_bridge: # Replace with a single Community Bridge project-name e.g., slack-foundry
liberapay: # Replace with a single Liberapay username UPS
issuehunt: # Replace with a single IssueHunt username Johnson
otechie: # Replace with a single Otechie username tor
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://libertymutal.com','https://mypillow.com','https://wallmart.com','https://iab.com']
